# Generated by Django 3.2.9 on 2021-11-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
