# Generated by Django 3.2.9 on 2021-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20211115_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='runnnig_time',
            new_name='runnig_time',
        ),
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
