# Generated by Django 3.2.9 on 2021-11-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211115_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='runnig_time',
            new_name='running_time',
        ),
    ]
